chan : Q_001
boris920308/QuestHouse pull request #4
Opened 2024-08-10 09:55 UTC by 000chan

ㅎㅎ

2024-08-11 09:26 UTC, boris920308 approved these changes

2024-08-11 09:26 UTC, boris920308 commented on Q_001_hello/chan/Solution2.java
> +        System.out.println(sb);
고수라 그런지 스트링빌더를 쓰시네

2024-08-11 09:26 UTC, boris920308 commented on Q_001_hello/chan/Solution1.java
> +        int ones     = num2       % 10 ;
줄간격 미쳤다 그곳 컨벤션은 이럼?

2024-08-12 00:25 UTC, boris920308 requested changes
커밋메시지 탈락

2024-08-12 00:56 UTC, 000chan commented
> 커밋메시지 탈락

2024-08-12 01:01 UTC, 000chan commented
.

2024-08-12 01:01 UTC, 000chan commented
.

2024-08-12 12:20 UTC, knm8643 commented
이야 영찬쿤 스프링 빌더를 써서 하다니.... 생각치도 못했어

2024-08-12 12:52 UTC, boris920308 approved these changes

2024-08-13 04:06 UTC, knm8643 reviewed
이쪽에다가 하는건가?

2024-08-13 04:07 UTC, knm8643 approved these changes
아 ㅋㅋ 확인했습니다

2024-08-13 04:07 UTC, merged